# Generated by Django 5.1.1 on 2024-09-07 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_alter_interest_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountprofile",
            name="city",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="accountprofile",
            name="passport_letter",
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name="accountprofile",
            name="passport_number",
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="accountprofile",
            unique_together={("passport_number", "passport_letter")},
        ),
    ]
