# Generated by Django 5.1.1 on 2024-09-07 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_accountprofile_city_accountprofile_passport_letter_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountprofile",
            name="passport_letter",
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name="accountprofile",
            name="passport_number",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
