# Generated by Django 5.1.1 on 2024-09-07 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_alter_accountprofile_passport_letter_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="accountprofile",
            unique_together=set(),
        ),
    ]
