# Generated by Django 5.1.1 on 2024-09-17 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0006_remove_account_interests_accountprofile_interests"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountprofile",
            name="avatar",
            field=models.ImageField(default="avatar.jpeg", upload_to="avatars/"),
        ),
    ]
