# Generated by Django 5.1.1 on 2024-09-17 15:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0008_remove_accountprofile_avatar_account_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="music",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="user-files/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["mp3", "ogg"]
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="rating",
            field=models.IntegerField(
                default=-1,
                validators=[
                    django.core.validators.MaxValueValidator(5),
                    django.core.validators.MinValueValidator(1),
                ],
            ),
            preserve_default=False,
        ),
    ]
