# Generated by Django 5.1.1 on 2024-09-17 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0009_account_music_account_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="role",
            field=models.CharField(
                choices=[("admin", "Admin"), ("user", "User")],
                default="user",
                max_length=5,
            ),
        ),
    ]
