# Generated by Django 5.1.1 on 2024-09-17 16:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0010_account_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="rating",
            field=models.IntegerField(
                default=-1,
                validators=[
                    django.core.validators.MaxValueValidator(5),
                    django.core.validators.MinValueValidator(1),
                ],
            ),
        ),
    ]
