# Generated by Django 5.1.1 on 2024-09-17 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0011_alter_account_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="phone",
            field=models.CharField(max_length=128),
        ),
    ]
