# Generated by Django 5.1.1 on 2024-09-17 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("poll", "0002_alter_poll_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="poll",
            options={},
        ),
    ]
