# Generated by Django 5.1.1 on 2024-09-19 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("poll", "0003_alter_poll_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="choice",
            name="answer",
        ),
        migrations.AddField(
            model_name="choice",
            name="audio",
            field=models.FileField(blank=True, null=True, upload_to="audios/"),
        ),
    ]
